### ISSUE TITLE
pip is unable to find pyomexmeta for Python 3.7

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/libOmexMeta#65]
Running `pip3.7 install pyomexmeta`

Leads to this error:
```
ERROR: Could not find a version that satisfies the requirement pyomexmeta (from versions: none)
ERROR: No matching distribution found for pyomexmeta
```

I was able to install pyomexmeta for Python 3.9.

**Comment by CiaranWelsh** [comment]
I'm not sure if you tried this before or after I released v1.2.6 - which just so happened to also be 3 days ago - but I suspect before. Could you try again and let me know if it works?

**Comment by jonrkarr** [comment]
I believe the issue is that the `manylinux2014` requires Python 3.7.8 or newer. I used 3.7.5. If you don't need features introduced at 3.7.6 or higher, `manylinux1` or `manylinux2010` would be more broadly compatible.

**Comment by CiaranWelsh** [comment]
Aaah I see. I don't think this is a many linux issue but a conda issue. When you do `conda create --name py37 python=3.7` conda automatically creates python 3.7.8 environment, which is the lowest I build against (checkout the azure_pipelines.yml to see how its built). 

(Also, I do need manylinux2014 since it has gcc 9.2 and therefore c++17 by default - which simplifies the CI quite a bit.)

**Comment by jonrkarr** [comment]
This page explains the version compatibility of the different linux tags: https://github.com/pypa/manylinux/blob/master/README.rst

manylinux2014 requires Python 3.7.8+, 3.8.4+, or 3.9.0+ and pip >= 19.3

**Comment by CiaranWelsh** [comment]
I think these refer to the Python versions that are installed on manylinux2014 by default. However since I'm using conda on manylinux2014 I can build against any Python version I want, including 3.7.5 apparently (since `conda create --name py375 python=3.7.5` works as you'd expect). 

Should I assume you need Python 3.7.5 because of some limiting dependency? If this is the case, I could add this version to my build matrix for the next release (coming this week). If not then I would prefer to stick with py3.7.8, given that I can't see that many people using such an outdated subversion anymore.

**Comment by jonrkarr** [comment]
I expected that 3.7.5 would work because earlier versions of 3.7 are still fairly new (e.g., 3.8 is only 1.5 years old). The issue can be closed. I would just suggest noting these version requirements in your installation instructions.

We don't specifically need 3.7.5. I happen to still have this on my Linux desktop. Everywhere else we're using 3.7.10 or 3.9.4.

**Comment by jonrkarr** [comment]
(The main reason we haven't switched to 3.9 is that there was a limiting dependency that didn't yet have a 3.8 or 3.9 version. Although this has since been resolved, I haven't gotten around to switching everything to 3.9.)

**Comment by CiaranWelsh** [comment]
Ah yes, okay - well thanks for posting the issue. I'll make sure I update the docs. Since I think its quite unusual to use a Python patch/micro version less than the latest release in the minor (aka 3.7.0 through to 3.7.7), and given how easy it is to update Python, my preferred response to this situation is to ask the user use an updated version of Python. I'd probably be doing them a favour anyway =]
