### ISSUE TITLE
RDF.from.file -- SBML annotation extraction doesn't always work

### ISSUE THREAD

**Issue by jhgennari** [sys-bio/libOmexMeta#71]
Alas, the RDF.from.file doesn't always produce the right annotations from SBML files. It works great on BIOMD #385, and it seems to work on other non-COPASI SBML files. Unfortunately, it fails on most (but not all) COPASI-generated files. 

Take a look at the attached output from BIOMD #626 (the zip includes both the SBML and the generated rdf). Check especially the dc:creator tags -- they have very weird arguments like "_:httpzzzwwwzw3zorgz1999z02z22zrdfzsyntaxznszz1"
[BIOMD-626.zip](https://github.com/sys-bio/libOmexMeta/files/6430142/BIOMD-626.zip)

If you want another examples of this behavior, it fails in a similar way on BIOMD #741 and #689. It seems to succeed on BIOMD #755, a COPASI-generated model. 

-jhg

**Comment by CiaranWelsh** [comment]
This turned out to be a bug in rdf:Bag translator. In short, sparql queries are used to detect rdf:Bag structures and then rearrange them. More effort and testing has gone into this feature ([see this commit](https://github.com/sys-bio/libOmexMeta/commit/3f3b18e6ced17c5a075235e118fd219306b14eab). Please use pyomexmeta `v1.2.8` for trying out the new code. 

Of note the only way to comprehensively test the rdf:Bag translator is to have tests for every edge case, which is not available to me. Therefore, if/when more problems with this arise, we'll have to take them in stride - eventually we'll get them all. Closing this issue until proven that it needs opening again.
